version: 2
updates:
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 7
    groups:
      production-deps:
        dependency-type: 'production'
        update-types: [minor, patch]
      development-deps:
        dependency-type: 'development'
        update-types: [minor, patch]
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      github-actions-updates:
        patterns: ['*']
    commit-message:
      prefix: 'chore(deps)'
