## @TODO:
#
# 1. Enable this workflow when the repo is public or the effort is greenlit a CI/CD budget.
# 2. Add a PHPCS-run step to test the rulesets against code.

name: Test Rulesets

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: read
  packages: read

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-rulesets:
    name: Test rulesets
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.5, 8.4, 8.3, 8.2, 8.1, 8.0, 7.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2.36.0
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, zip
          tools: composer:v2
          # Allow for PHP deprecation notices.
          ini-values: error_reporting = E_ALL & ~E_DEPRECATED
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate composer.json file
        run: composer validate --no-check-all --strict

      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4.0.0
        with:
          # Bust the cache at least once a month - output format: YYYY-MM.
          custom-cache-suffix: $(date -u "+%Y-%m")

      # Validate the Ruleset XML files.
      - name: Validate the WordPress rulesets
        uses: phpcsstandards/xmllint-validate@0fd9c4a9046055f621fca4bbdccb8eab1fd59fdc # v1.0.1
        with:
          pattern: './*/ruleset.xml'
          xsd-file: 'vendor/squizlabs/php_codesniffer/phpcs.xsd'
